name: reading-pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  quality:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Show list of updated files
      run: |
        git diff --name-only --diff-filter=d ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} ${{ github.event.pull_request.head.sha }}
        echo "-$(git diff --name-only --diff-filter=d ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} ${{ github.event.pull_request.head.sha }} | grep "^configs/.*/.*\.[yY][aA]*[mM][lL]$")-"
    - name: Select only the files under configs
      id: get-files
      run: |
        echo "list=$(git diff --name-only --diff-filter=d ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} ${{ github.event.pull_request.head.sha }} | grep "^configs/.*/.*\.[yY][aA]*[mM][lL]$")" >> "$GITHUB_OUTPUT"
    - name: Copy new files to tmp directory
      if: ${{ steps.get-files.outputs.list != '' }}
      run: |
        echo ${{ steps.get-files.outputs.list }}
        mkdir check_dir
        echo ${{ steps.get-files.outputs.list }} | sed "s|^|"$(pwd)"\/|" | xargs cp --parents -s -t check_dir/
    - name: List new files
      if: ${{ steps.get-files.outputs.list != '' }}
      run: |
        ls check_dir/*/*