name: 'scheduled-job-actions'
on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Update timmys
        run: |
            curl -X GET http://shoulditestprivatemethods.com > timmys.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Fernando Ocampo
          branch: master
          message: 'add new content'

